<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.4"/>
        <!--- Testing -->
        <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.0"/>
        <PackageVersion Include="NSubstitute" Version="6.2.0"/>
        <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.0"/>
    </ItemGroup>

</Project>
