<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Microsoft.Extensions.Caching.Hybrid" Version="10.10.0"/>
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12"/>
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12"/>
        <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12"/>
        <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.12"/>
        <!--- Testing -->
        <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2"/>
        <PackageVersion Include="NSubstitute" Version="6.2.0"/>
        <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.1"/>
    </ItemGroup>

</Project>
