trigger:
  branches:
    exclude:
      - master
      - gh-pages
  paths:
    exclude:
      - '.github'
      - docs
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md

variables:
  - template: variables.yml

stages:
  - stage: Build
    displayName: 🚧 Build
    jobs:
      - job: Build
        displayName: Build with .NET Core SDK
        pool:
          vmImage: $(vmImage)
        steps:
          - task: UseDotNet@2
            displayName: Install .NET SDK
            inputs:
              packageType: sdk
              version: $(netSdkVersion)
          - task: gitversion/setup@0
            displayName: 'Setup git version'
            inputs:
              versionSpec: '5.x'

          - task: gitversion/execute@0
            displayName: 'Calculate git version'
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              additionalArguments: '/updateprojectfiles'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '$(projectPath)
              arguments: '--configuration $(buildConfiguration) --no-restore'
              versioningScheme: byEnvVar
              versionEnvVar: 'GitVersion.SemVer'
              displayName: 'Build projects [$(buildConfiguration)]'
          
          - task: DotNetCoreCLI@2
            displayName: 'Create NuGet package'
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj;!**/*.Test.csproj'
              versioningScheme: 'byEnvVar'
              versionEnvVar: 'GitVersion.NuGetVersion'
              packDestination: $(Build.ArtifactStagingDirectory)/packages
              configuration: $(buildConfiguration)
            
          - publish: $(Build.ArtifactStagingDirectory)/packages
            artifact: packages
  - stage: Test
    dependsOn: Build
    displayName: 🧪 Test
    jobs:
      - job: Test
        displayName: Run test
        pool:
          vmImage: ubuntu-22.04
        steps:
          - task: UseDotNet@2
            displayName: Install .NET sdk
            inputs:
              packageType: sdk
              version: $(netSdkVersion)

          - task: DotNetCoreCLI@2
            displayName: 'Run unit tests'
            inputs:
            command: 'test'
            projects: '**/*.@(Test|Tests).csproj'
            arguments: >-
              --no-build
              --configuration ${{ parameters.buildConfiguration }}
              --logger "trx;LogFileName=testresults.trx"
            publishTestResults: true

  - stage: PublishArtifacts
    dependsOn: Build
    displayName: 📤 Publish artifacts
    jobs:
      - job: PublishArtifacts
        displayName: Publish artifacts
        pool:
          vmImage: ubuntu-22.04
        steps:
          - checkout: none
          - download: current
            artifact: packages
          - task: UseDotNet@2
            displayName: Install .NET sdk
            inputs:
              packageType: sdk
              version: $(netSdkVersion)
          - task: NuGetAuthenticate@1
            displayName: 'NuGet Authenticate'
          - task: NuGetCommand@2
            displayName: Publish CI package to Azure artifacts
            inputs:
              command: 'push'
              packagesToPush: $(Pipeline.Workspace)/packages/*.*upkg
              nuGetFeedType: 'internal'
              vstsFeed: $(internalFeedName)
              publishVstsFeed: $(internalFeedName)
              allowPackageConflicts: true