name: .NET Continuous Integration

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  test:
    name: Testing Solution
    runs-on: ubuntu-latest
    permissions:
          id-token: write
          contents: read
          checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup git verison
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Calcuate git version
        uses: gittools/actions/gitversion/execute@v0
      - name: Display git version
        run: |
          echo "NuGetVersion: ${{ env.nuGetVersion }}"
          echo "NuGetPreReleaseTag: ${{ env.nuGetPreReleaseTag }}"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Test
        run: dotnet test --logger "trx;LogFileName=test-results.trx" ./src/Flickr.Net.sln
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()   # run this step even if previous step failed
        with:
          name: Dotnet Tests            # Name of the check run which will be created
          path: "**/test-results.trx"  # Path to test results
          reporter: dotnet-trx        # Format of test results
          fail-on-error: true
